<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['clearcenter_app_description'] = 'Базовая система предоставляет базовый набор инструментов для программного обеспечения от ClearCenter.';
$lang['clearcenter_app_name'] = 'База ClearCenter ';
$lang['clearcenter_connecting_to_clearcenter'] = 'Соединение с ClearCenter...';
$lang['clearcenter_connection_failed:'] = 'Связь прервалась:';
$lang['clearcenter_dns_lookup_failed'] = 'Ошибка при поиске DNS.';
$lang['clearcenter_information_from_remote_network_not_available'] = 'Информация от удаленной сети не доступна.';
$lang['clearcenter_remaining_user_licenses:'] = 'Оставшееся пользовательские лицензии:';
$lang['clearcenter_service_is_up_to_date'] = 'Служба актуальна.';
$lang['clearcenter_service_requires_an_update'] = 'Служба требует обновления.';
$lang['clearcenter_service_update_failed:'] = 'Обновление службы не удалось:';
$lang['clearcenter_subscription_update_complete'] = 'Подписка обновлений закончилась';
$lang['clearcenter_system_not_registered'] = 'Система не зарегистрирована.';
$lang['clearcenter_unable_to_contact_remote_server'] = 'Не удается связаться с удаленным сервером.';
