<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['clearcenter_app_description'] = 'Podstawowy system dostarcza podstawowych narzędzi oprogramowania od ClearCenter.';
$lang['clearcenter_app_name'] = 'Podstawa ClearCenter';
$lang['clearcenter_connecting_to_clearcenter'] = 'Łączenie z ClearCenter...';
$lang['clearcenter_connection_failed:'] = 'Połączenie nieudane:';
$lang['clearcenter_dns_lookup_failed'] = 'Rozpoznanie DNS nie udało się.';
$lang['clearcenter_information_from_remote_network_not_available'] = 'Informacja z sieci zdalnej nie jest dostępna.';
$lang['clearcenter_remaining_user_licenses:'] = 'Pozostałe licencje użytkownika:';
$lang['clearcenter_service_is_up_to_date'] = 'Usługa jest aktualna.';
$lang['clearcenter_service_requires_an_update'] = 'Usługa wymaga aktualizacji.';
$lang['clearcenter_service_update_failed:'] = 'Aktualizacja usługi nieudała się:';
$lang['clearcenter_subscription_update_complete'] = 'Aktualizacja subskrypcji zakończona';
$lang['clearcenter_system_not_registered'] = 'System nie jest zarejestrowany.';
$lang['clearcenter_unable_to_contact_remote_server'] = 'Nie można skontaktować się ze zdalnym serwerem.';
