<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['clearcenter_app_description'] = 'Ang pundasyon ng sistema ay nagbibigay ng isang pangunahing hanay ng mga tool para sa software mula sa ClearCenter.';
$lang['clearcenter_app_name'] = 'ClearCenter Pundasyon';
$lang['clearcenter_connecting_to_clearcenter'] = 'Kumokonekta sa ClearCenter...';
$lang['clearcenter_connection_failed:'] = 'Nabigo ang koneksyon:';
$lang['clearcenter_dns_lookup_failed'] = 'Nabigo ang paghanap sa pamamagitan DNS.';
$lang['clearcenter_information_from_remote_network_not_available'] = 'Impormasyon mula sa malayong network ay hindi magagamit.';
$lang['clearcenter_remaining_user_licenses:'] = 'Remaining User Licenses:';
$lang['clearcenter_service_is_up_to_date'] = 'Service is up-to-date.';
$lang['clearcenter_service_requires_an_update'] = 'Nangangailangan ng serbisyo ng mapagbago.';
$lang['clearcenter_service_update_failed:'] = 'Nabigo ang maipagbago sa serbisyo.';
$lang['clearcenter_subscription_update_complete'] = 'Subscription update complete';
$lang['clearcenter_system_not_registered'] = 'System is not registered.';
$lang['clearcenter_unable_to_contact_remote_server'] = 'Unable to contact remote server.';
